"""create audit_logs table

Enterprise Audit Framework (Module 1).

Hand-written rather than autogenerated on purpose: `alembic revision
--autogenerate` inspects the whole metadata, and this project's
`embeddings` table uses pgvector's Vector(1536) type, which autogenerate
does not round-trip cleanly — it emits spurious ALTER/DROP operations
against tables this change has nothing to do with. Writing the migration
by hand guarantees it touches ONLY the new table.

Purely additive: creates one new table and its indexes. No existing
table, column, constraint or index is read, altered or dropped, so the
downgrade is a clean, complete reversal.

Revision ID: c1d2e3f4a5b6
Revises: b2c3d4e5f6a7
Create Date: 2026-08-05
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = 'c1d2e3f4a5b6'
down_revision: Union[str, Sequence[str], None] = 'b2c3d4e5f6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        'audit_logs',

        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),

        # Event time. server_default=now() as a safety net so a row can
        # never be written without one, even by a direct SQL insert.
        sa.Column(
            'timestamp',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False
        ),

        # ondelete='SET NULL', never CASCADE — removing a user must not
        # remove the record of what that user did. user_email below keeps
        # the identity readable afterwards.
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('user_email', sa.String(length=320), nullable=True),
        sa.Column('role', sa.String(length=32), nullable=True),
        sa.Column('customer_id', sa.Integer(), nullable=True),

        sa.Column('category', sa.String(length=64), nullable=False),
        sa.Column('action', sa.String(length=128), nullable=False),
        sa.Column('resource', sa.String(length=128), nullable=True),
        sa.Column('resource_id', sa.String(length=128), nullable=True),
        sa.Column('status', sa.String(length=32), nullable=False),

        # JSONB (not JSON) so it is GIN-indexable — that index is what
        # makes future "advanced filters" over event metadata possible
        # without a schema redesign.
        sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),

        sa.Column('request_id', sa.String(length=64), nullable=True),
        sa.Column('ip_address', sa.String(length=64), nullable=True),
        sa.Column('user_agent', sa.String(length=512), nullable=True),
        sa.Column('session_id', sa.String(length=128), nullable=True),

        sa.Column('http_method', sa.String(length=10), nullable=True),
        sa.Column('http_path', sa.String(length=512), nullable=True),
        sa.Column('http_status', sa.Integer(), nullable=True),
        sa.Column('duration_ms', sa.Integer(), nullable=True),

        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=False
        ),

        sa.PrimaryKeyConstraint('id'),

        sa.ForeignKeyConstraint(
            ['user_id'], ['users.id'],
            name='fk_audit_logs_user_id',
            ondelete='SET NULL'
        ),
        sa.ForeignKeyConstraint(
            ['customer_id'], ['customers.id'],
            name='fk_audit_logs_customer_id',
            ondelete='SET NULL'
        )
    )

    # Every index is (dimension, timestamp DESC) rather than a plain
    # single-column index, because every realistic audit query is
    # "filter by one dimension, newest first, paginated". A single-column
    # index would satisfy the filter but still force a sort.
    op.create_index(
        'ix_audit_logs_timestamp',
        'audit_logs',
        [sa.text('timestamp DESC')]
    )
    op.create_index(
        'ix_audit_logs_category_timestamp',
        'audit_logs',
        ['category', sa.text('timestamp DESC')]
    )
    op.create_index(
        'ix_audit_logs_action_timestamp',
        'audit_logs',
        ['action', sa.text('timestamp DESC')]
    )
    op.create_index(
        'ix_audit_logs_user_id_timestamp',
        'audit_logs',
        ['user_id', sa.text('timestamp DESC')]
    )
    op.create_index(
        'ix_audit_logs_status_timestamp',
        'audit_logs',
        ['status', sa.text('timestamp DESC')]
    )

    # Single-column: used for exact-match request correlation, which
    # needs no ordering.
    op.create_index('ix_audit_logs_request_id', 'audit_logs', ['request_id'])

    # "Show me everything that happened to document 42".
    op.create_index(
        'ix_audit_logs_resource',
        'audit_logs',
        ['resource', 'resource_id']
    )

    # GIN over the JSONB payload — enables containment queries on event
    # metadata (details @> '{"reason": "invalid_password"}') for the
    # future advanced-filter and SIEM-export requirements.
    op.create_index(
        'ix_audit_logs_details',
        'audit_logs',
        ['details'],
        postgresql_using='gin'
    )


def downgrade() -> None:
    op.drop_index('ix_audit_logs_details', table_name='audit_logs')
    op.drop_index('ix_audit_logs_resource', table_name='audit_logs')
    op.drop_index('ix_audit_logs_request_id', table_name='audit_logs')
    op.drop_index('ix_audit_logs_status_timestamp', table_name='audit_logs')
    op.drop_index('ix_audit_logs_user_id_timestamp', table_name='audit_logs')
    op.drop_index('ix_audit_logs_action_timestamp', table_name='audit_logs')
    op.drop_index('ix_audit_logs_category_timestamp', table_name='audit_logs')
    op.drop_index('ix_audit_logs_timestamp', table_name='audit_logs')
    op.drop_table('audit_logs')
