"""add cascade delete to documents

Revision ID: da04cf253e93
Revises: ca36f37bdc31
Create Date: 2026-07-02 12:05:30.110050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da04cf253e93'
down_revision: Union[str, Sequence[str], None] = 'ca36f37bdc31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('document_chunks_document_id_fkey'), 'document_chunks', type_='foreignkey')
    op.create_foreign_key(None, 'document_chunks', 'documents', ['document_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('embeddings_chunk_id_fkey'), 'embeddings', type_='foreignkey')
    op.create_foreign_key(None, 'embeddings', 'document_chunks', ['chunk_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('semantic_cache_embedding_idx'), table_name='semantic_cache', postgresql_ops={'question_embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('semantic_cache_embedding_idx'), 'semantic_cache', ['question_embedding'], unique=False, postgresql_ops={'question_embedding': 'vector_cosine_ops'}, postgresql_with={'lists': '100'}, postgresql_using='ivfflat')
    op.drop_constraint(None, 'embeddings', type_='foreignkey')
    op.create_foreign_key(op.f('embeddings_chunk_id_fkey'), 'embeddings', 'document_chunks', ['chunk_id'], ['id'])
    op.drop_constraint(None, 'document_chunks', type_='foreignkey')
    op.create_foreign_key(op.f('document_chunks_document_id_fkey'), 'document_chunks', 'documents', ['document_id'], ['id'])
    # ### end Alembic commands ###
