"""add_is_super_admin_to_users

Revision ID: ff69ac9ff84c
Revises: ef44cfe1b32e
Create Date: 2026-06-25 10:15:35.975400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff69ac9ff84c'
down_revision: Union[str, Sequence[str], None] = 'ef44cfe1b32e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_super_admin', sa.Boolean(), nullable=False,server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_super_admin')
    # ### end Alembic commands ###
